### ISSUE TITLE
java.lang.NoSuchMethodError: meldexun.reachfix.hook.client.EntityRendererHook.pointedObject

### ISSUE THREAD

**Issue by eggmanpoop** [fonnymunkey/RLCombat#1]
[crash-2022-12-25_03.17.43-client.txt](https://github.com/fonnymunkey/RLCombat/files/10299600/crash-2022-12-25_03.17.43-client.txt)
So whenever I swing any weapon I just crash instantly. Not sure which mods are incompatible though

**Comment by fonnymunkey** [comment]
Latest ReachFix has been uploaded to Curseforge, updating ReachFix will resolve this.
