### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vaaticuz** [fonnymunkey/RLCombat#12]
Crashes when joining a world, with the new version.
[crash-2024-08-27_16.23.40-client.txt](https://github.com/user-attachments/files/16770653/crash-2024-08-27_16.23.40-client.txt)

**Comment by fonnymunkey** [comment]
Can you upload your latest.log file from the logs folder from this crash?

**Comment by Vaaticuz** [comment]
Sure. 
[latest.log](https://github.com/user-attachments/files/16770687/latest.log)

**Comment by fonnymunkey** [comment]
It would appear that a mixin accessor is failing to apply or be registered, however I do not see a direct reason for why from your logs.

There are a couple other mixin errors in your log as well, perhaps try using Java 8 or a non-cleanroom loader to see if you still have the issue.

I would assume it is likely an issue related to either Cleanroom Loader or it being newer Java, or both.

I attempted to recreate your enviroment myself on Curseforge and Java 8 and was able to load and use RLCombat fine without the same issues.

**Comment by Vaaticuz** [comment]
ok ty

**Comment by fonnymunkey** [comment]
As an update, I was able to reproduce this issue, and it is an issue related specifically to Cleanroom Loader 0.2.3 and whatever changed in that update causing mixins loaded by FermiumBooter to silently fail to apply with no error as to why.

As 0.2.3 released only a week ago, its possible its an issue with the release itself, or an new incompatibility introduced that needs to be fixed, that I can look into when I get time.

0.2.2 and previous work fine with RLCombat and Fermium however, so if you desire to use both latest RLCombat and Cleanroom you can downgrade to 0.2.2 for the time being.

**Comment by fonnymunkey** [comment]
FermiumBooter 1.1.1 should fix this issue and provide compat with Cleanroom Loader 0.2.3, its been uploaded to all sites and is currently awaiting approval.
