### ISSUE TITLE
[A-BUG] Crash when attacking

### ISSUE THREAD

**Issue by Xarmat-GitHub** [fonnymunkey/RLCombat#2]
Hello, when I left click (in the air, targeting entity or block) the game instantly crashes.
Mods installed:
- ReachFix-1.12.2-1.0.6
- RLCombat-1.12.2-2.0.4

Forge Version: 14.23.5.2859

Do I miss something?

**Comment by fonnymunkey** [comment]
Latest ReachFix has been uploaded to Curseforge, updating ReachFix will resolve this.
