### ISSUE TITLE
Feature request: removing off hand swing if any interaction with the main hand is happening & improving "Attacks require full energy" option logic.

### ISSUE THREAD

**Issue by GrandeMalum** [fonnymunkey/RLCombat#4]
Personal request: please, if you'll have time, change the way offhand combat works while using some kind of interactable item in main hand or right clicking some kind of interactable block, like chest. Lets say Im trying to shoot something with the bow, and then suddenly an attack from my offhand appears at the same time, making a sweeping sound if DynamicSorroundings mod is present. Same happens when I'm trying to eat, drink, place blocks, make a dirt path with a shovel, throw something like snowball or throwing axe from spartan weaponry and etc in my main hand. This change will make playing with this mod drastically less annoying.

Also the logic of "Attacks require full energy" option seems a bit strange to me because spam attacking with the offhand and main hand is different. For now I'm using a standalone mod (ExhaustedStamina) which makes main hand cooldown the same as the offhand one, without the ability to spam click with the main hand if the player is aiming at a block while attacking or is trying to break it.

**Comment by Turkey9002** [comment]
An item blacklist for offhand attacking would be pretty nice to have like how there's a whitelist already.

**Comment by fonnymunkey** [comment]
As of 2.2.0, swinging your offhand while trying to use a mainhand item or interact with something should be fixed (Unless the swing would actually attack an entity, to allow for defensive tactics.)
Additionally offhand hitting both for iframe and cooldown should now be fixed and properly match the logic of mainhand.
There is also now an item id blacklist to disable specific weapons from offhand.
