### ISSUE TITLE
Sounds do not play.

### ISSUE THREAD

**Issue by MagmaBro123** [fonnymunkey/RLCombat#6]
Title. No other mods are in use.

![image](https://user-images.githubusercontent.com/51277766/216850557-30112c25-7303-4be4-af26-a2769dccb665.png)

**Comment by fonnymunkey** [comment]
Ensure "Additional Hit Sounds" and "Additional Crit Sounds" are enabled in the config, they should be enabled by default.

I can not recreate sounds not working on a fresh install without purposefully turning off the config option, both vanilla and spartan weapons play the sounds correctly.

**Comment by MagmaBro123** [comment]
Both are enabled.

**Comment by fonnymunkey** [comment]
Does it play any hit/crit sounds, like the default ones, or none at all?
Is this with any weapon, or specific to certain weapons?
On server or singleplayer, or both?

**Comment by MagmaBro123** [comment]
Both, no sounds at all, any weapon.

**Comment by fonnymunkey** [comment]
If you're not hearing any sounds from weapons then that sounds like an issue external to the mod, either a problem in your sounds settings, or with the game/drivers itself.

**Comment by MagmaBro123** [comment]
Well, all other sounds play correctly. Music, etc.

**Comment by MagmaBro123** [comment]
To add, BetterCombatRebirth's new sounds work just fine.

**Comment by fonnymunkey** [comment]
I've changed nothing to do with sounds, they are still exactly the same as BetterCombatRebirth. 
I have been unable to replicate sounds not playing without either disabling them in the config, disabling sounds in the sounds settings, or some other mod cancelling/breaking RLCombat's attack handling entirely.
Likewise, none of the hundreds of RLCraft testers have reported missing attack sounds as well so far, so I have no idea what is causing your issue.

**Comment by MagmaBro123** [comment]
Me neither. The modlist above is all I have right now.

**Comment by fonnymunkey** [comment]
As of 2.2.0 the whole sound system has been reworked, and additionally I have never been able to reproduce this issue nor had any other instances of it happening, so Im going to assume it will be resolved with the latest version.
