### ISSUE TITLE
Using the opposite hand's sword right after using a sword will cancel that sword's attack out.

### ISSUE THREAD

**Issue by MagmaBro123** [fonnymunkey/RLCombat#7]
Title. This is better explained in video, this does not happen with BetterCombatRebirth.

At 19:00, not quickly using the sword after the mainhand's sword won't cause issues.

Happens with or without other mods.

https://user-images.githubusercontent.com/51277766/224033891-d91d6e34-8fa6-41bc-895f-ce4c908df7c5.mp4

**Comment by MagmaBro123** [comment]
Ah. Well, could mark this as a todo if needed.

**Comment by fonnymunkey** [comment]
This will be fixed both with and without custom animations enabled in 2.2.0.
