### ISSUE TITLE
Attack cooldown does not work.

### ISSUE THREAD

**Issue by yeemvrother** [fonnymunkey/RLCombat#9]
Using latest version of RLCombat, the option preventing players from attacking until the cooldown bar is full does not work. I have tested both modded items (spartan weaponry, which requires this mod), as well as vanilla weapons. I have the option checked and it does not prevent swinging until the bar is full as it should.

**Comment by fonnymunkey** [comment]
I just loaded up a heavily modded instance and tested, and it still works for me.
Both offhand and mainhand can't hit if cooldown is active (However, the cooldowns are separate for each hand.)

Do you have any other mods installed that could be modifying how combat works?

**Comment by yeemvrother** [comment]
I don't believe so. Only other mod I have that affects players movements and stuff are reach fix and elenai dodge. Besides that it's just mods that add blocks or npcs. It seems to work randomly some times and stop working other times.

**Comment by fonnymunkey** [comment]
Is it both hands or only one hand that does it? 
Any specific entities or all of them? 
Server or singleplayer?

Anything besides that, I would need a latest.log and/or modlist to figure out any other mods that could be messing with it.

**Comment by yeemvrother** [comment]
It seems to be this way in both hands, but I am keeping lefthand attack disabled for my specific modpack. Doing singleplayer, and I have tried it on both modded entities (customnpcs) and vanilla. It also does not work when punching the air. Should I send a log or list?

**Comment by fonnymunkey** [comment]
Yea, launch the game, get the bug to happen, close it, and upload the latest.log

**Comment by yeemvrother** [comment]
The mod seems to randomly work... This time it mostly did, although when I killed the squid before closing the game, it let me hit again before the bar was full. It seems that most of the time it doesn't work is when I'm hitting the air or blocks, but it occasionally seems to not work with npcs. Not sure if this is intended behavior or not. If it's not something fixable, no worries!

[latest.log](https://github.com/fonnymunkey/RLCombat/files/11750426/latest.log)

**Comment by fonnymunkey** [comment]
You are still on SpartanWeaponry 1.5.1, 1.5.3 is the version that overhauled to add compatibility for RLCombat and Reachfix.

Old SpartanWeaponry did its own custom checks for hitting entities to handle stuff like reach modifiers, which why it seems like only some times it bypasses the cooldown, because Spartan is seeing you hit the entity but not RLCombat/Reachfix 
(We had this same issue in RLCraft before compat was added.)

Updating to 1.5.3 should fix this issue.

**Comment by yeemvrother** [comment]
Oh, thank you. I swear I downloaded the most recent build for 1.12 but I guess not...

**Comment by fonnymunkey** [comment]
Closing as previously resolved.
